# Generated by Django 4.2.7 on 2025-03-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_techniciannotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniciannotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación de Técnico', 'verbose_name_plural': 'Notificaciones de Técnicos'},
        ),
        migrations.AlterField(
            model_name='techniciannotification',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket'),
        ),
    ]
